spring.application.name=demo
server.port=1234
spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceWeb_side
spring.datasource.username=root
spring.datasource.password=221579
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
project.image=C:/Users/pankaj kumar saini/Documents/Ecommerce/images/
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=java71932@gmail.com
spring.mail.password=pnypuuiuaohomgla
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
